"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import {
  blockDate, createBooking, createClient, createTournament, deleteBooking, deleteTournament,
  signOut, updateBooking, updateClient, updateTournament,
} from "./actions";

type Row = Record<string, any>;
type View = "dashboard" | "availability" | "bookings" | "clients" | "tournaments" | "payments" | "invoices" | "maintenance";
type ModalState = { type: "booking" | "client" | "block" | "tournament"; record?: Row; defaults?: Row } | null;
type Data = { bookings: Row[]; clients: Row[]; expenses: Row[]; invoices: Row[]; maintenance: Row[]; blocked: Row[]; collections: Row[]; ledger: Row[]; tournaments: Row[] };

const LAUNCH_DATE = "2026-10-01";
const SLOTS = ["07:00", "10:30", "14:00"];
const money = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n || 0);
const date = (d: string | null) => d ? new Date(`${d}T12:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const iso = (value: Date) => value.toISOString().slice(0, 10);
const addDays = (value: string, days: number) => { const d = new Date(`${value}T12:00:00`); d.setDate(d.getDate() + days); return iso(d); };
const time = (value: string | null) => value ? String(value).slice(0, 5) : "—";

export function DashboardClient({ data, today }: { data: Data; today: string }) {
  const [view, setView] = useState<View>("dashboard");
  const [modal, setModal] = useState<ModalState>(null);
  const [search, setSearch] = useState("");
  const [timeline, setTimeline] = useState("since-launch");
  const [customFrom, setCustomFrom] = useState(LAUNCH_DATE);
  const [customTo, setCustomTo] = useState(today);
  const [bookingStatus, setBookingStatus] = useState("All");
  const [bookingSlot, setBookingSlot] = useState("All");
  const [paymentStatus, setPaymentStatus] = useState("All");
  const [bookingFrom, setBookingFrom] = useState("");
  const [bookingTo, setBookingTo] = useState("");
  const [calendarStart, setCalendarStart] = useState(today);

  const range = useMemo(() => {
    if (timeline === "all") return { from: "", to: "" };
    if (timeline === "custom") return { from: customFrom, to: customTo };
    if (timeline === "7d") return { from: addDays(today, -6), to: today };
    if (timeline === "30d") return { from: addDays(today, -29), to: today };
    if (timeline === "month") return { from: today.slice(0, 8) + "01", to: today };
    return { from: LAUNCH_DATE, to: "" };
  }, [timeline, customFrom, customTo, today]);

  const inRange = (value: string | null) => Boolean(value && (!range.from || value >= range.from) && (!range.to || value <= range.to));
  const dashboardBookings = data.bookings.filter(b => inRange(b.booking_date));
  const dashboardCollections = data.collections.filter(c => inRange(c.collection_date));
  const dashboardExpenses = data.expenses.filter(e => inRange(e.expense_date));
  const totals = useMemo(() => ({
    income: dashboardBookings.reduce((s, b) => s + Number(b.collected_amount || 0), 0) + dashboardCollections.reduce((s, c) => s + Number(c.amount || 0), 0),
    quoted: dashboardBookings.reduce((s, b) => s + Number(b.total_amount || 0), 0),
    balance: dashboardBookings.reduce((s, b) => s + Number(b.balance_amount || 0), 0),
    expenses: dashboardExpenses.reduce((s, e) => s + Number(e.amount || 0), 0),
  }), [dashboardBookings, dashboardCollections, dashboardExpenses]);

  const filteredBookings = useMemo(() => data.bookings
    .filter(b => Object.values(b).join(" ").toLowerCase().includes(search.toLowerCase()))
    .filter(b => bookingStatus === "All" || b.status === bookingStatus)
    .filter(b => bookingSlot === "All" || time(b.slot) === bookingSlot)
    .filter(b => paymentStatus === "All" || b.payment_status === paymentStatus)
    .filter(b => !bookingFrom || b.booking_date >= bookingFrom)
    .filter(b => !bookingTo || b.booking_date <= bookingTo)
    .sort((a, b) => `${b.booking_date}${b.slot}`.localeCompare(`${a.booking_date}${a.slot}`)),
  [data.bookings, search, bookingStatus, bookingSlot, paymentStatus, bookingFrom, bookingTo]);

  const upcoming = data.bookings.filter(b => b.booking_date >= today && b.status !== "Cancelled")
    .sort((a, b) => `${a.booking_date}${a.slot}`.localeCompare(`${b.booking_date}${b.slot}`)).slice(0, 7);
  const nav: [View, string, string][] = [
    ["dashboard", "⌂", "Overview"], ["availability", "▦", "Slot calendar"], ["bookings", "◫", "Bookings"],
    ["clients", "♙", "Clients"], ["tournaments", "♛", "Tournaments"], ["payments", "₹", "Payments"],
    ["invoices", "▤", "Invoices"], ["maintenance", "◇", "Maintenance"],
  ];

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><Image src="/kcc-logo.jpeg" alt="KCC" width={50} height={50}/><div><strong>KCC</strong><span>Ground Admin</span></div></div>
      <nav>{nav.map(([id, icon, label]) => <button key={id} className={`nav-item ${view === id ? "active" : ""}`} onClick={() => setView(id)}><span className="nav-icon">{icon}</span>{label}{id === "bookings" && <span className="nav-count">{data.bookings.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="season-card"><span>SECURE ACCESS</span><strong>KCC administrator</strong><div className="progress"><i style={{ width: "100%" }}/></div><small>Authenticated database session</small></div><form action={signOut}><button className="profile-card"><span className="avatar">KCC</span><span><strong>KCC Admin</strong><small>Administrator</small></span><span>↪</span></button></form></div>
    </aside>
    <main className="main"><header className="topbar"><div className="search"><span>⌕</span><input placeholder="Search current view…" value={search} onChange={e => setSearch(e.target.value)}/></div><div className="top-actions"><button className="date-chip"><span>Secure session</span><strong>KCC Ground Admin</strong></button></div></header><div className="content">
      {view === "dashboard" && <><Header eyebrow="GROUND OPERATIONS" title="KCC operations dashboard" subtitle="Collections and activity from 01 October 2026 onward, with flexible reporting periods." actions={<><button className="secondary-button" onClick={() => setModal({ type: "block" })}>＋ Block date</button><button className="primary-button" onClick={() => setModal({ type: "booking" })}>＋ New booking</button></>}/><TimelineFilter value={timeline} setValue={setTimeline} from={customFrom} to={customTo} setFrom={setCustomFrom} setTo={setCustomTo}/><div className="metric-grid"><Metric label="TOTAL COLLECTED" value={money(totals.income)} note="Booking and other collections in period" icon="₹"/><Metric label="TOTAL QUOTED" value={money(totals.quoted)} note="Quoted booking value in period" icon="↗"/><Metric label="BALANCE DUE" value={money(totals.balance)} note="Open booking balances" icon="◷"/><Metric label="OPERATING EXPENSES" value={money(totals.expenses)} note="Expenses with dates in period" icon="⌁"/></div><div className="dashboard-grid"><Panel title="Upcoming schedule"><Schedule rows={upcoming}/></Panel><Panel title="Quick actions"><div className="quick-actions"><button className="quick-action" onClick={() => setModal({ type: "booking" })}><span>＋</span>New booking</button><button className="quick-action" onClick={() => setView("availability")}><span>▦</span>Check slots</button><button className="quick-action" onClick={() => setModal({ type: "client" })}><span>♙</span>Add client</button><button className="quick-action" onClick={() => setModal({ type: "tournament" })}><span>♛</span>Add tournament</button></div></Panel></div></>}
      {view === "availability" && <><Header eyebrow="GROUND CALENDAR" title="Slot availability" subtitle="Booked, blocked, and open ground slots at a glance." actions={<><button className="secondary-button" onClick={() => setModal({ type: "block" })}>＋ Block date</button><button className="primary-button" onClick={() => setModal({ type: "booking" })}>＋ New booking</button></>}/><AvailabilityCalendar start={calendarStart} setStart={setCalendarStart} today={today} bookings={data.bookings} blocked={data.blocked} onBook={(bookingDate, slot) => setModal({ type: "booking", defaults: { booking_date: bookingDate, slot } })}/></>}
      {view === "bookings" && <><Header eyebrow="SCHEDULE" title="Bookings" subtitle="Newest bookings appear first. Filter, edit, settle, or remove any record." actions={<button className="primary-button" onClick={() => setModal({ type: "booking" })}>＋ New booking</button>}/><BookingFilters status={bookingStatus} slot={bookingSlot} payment={paymentStatus} from={bookingFrom} to={bookingTo} setStatus={setBookingStatus} setSlot={setBookingSlot} setPayment={setPaymentStatus} setFrom={setBookingFrom} setTo={setBookingTo}/><BookingTable rows={filteredBookings} onEdit={record => setModal({ type: "booking", record })}/></>}
      {view === "clients" && <><Header eyebrow="CLIENT CRM" title="Clients" subtitle="Select Edit to update contact, team, status, or notes." actions={<button className="primary-button" onClick={() => setModal({ type: "client" })}>＋ Add client</button>}/><ClientTable rows={data.clients.filter(c => Object.values(c).join(" ").toLowerCase().includes(search.toLowerCase()))} onEdit={record => setModal({ type: "client", record })}/></>}
      {view === "tournaments" && <><Header eyebrow="TOURNAMENT DESK" title="Tournaments" subtitle="Upcoming tournament dates, timings, format, organizer, and contact details." actions={<button className="primary-button" onClick={() => setModal({ type: "tournament" })}>＋ Add tournament</button>}/><TournamentGrid rows={data.tournaments} onEdit={record => setModal({ type: "tournament", record })}/></>}
      {view === "payments" && <><Header eyebrow="FINANCE" title="Payments" subtitle="Workbook collections, booking receipts, tournament expenses, and partner ledger entries."/><Panel title="Collection ledger"><DataTable headers={["Date", "Client / source", "Description", "Slot", "Amount"]} rows={data.collections.map(c => [date(c.collection_date), c.client_name || c.category, c.description, c.slot || "—", money(c.amount)])}/></Panel><Panel title="Operating expenses"><DataTable headers={["Date", "Expense", "Category", "Amount", "Status"]} rows={data.expenses.map(e => [date(e.expense_date), e.item, e.category, money(e.amount), e.status])}/></Panel><Panel title="Partner and season ledger"><DataTable headers={["Party", "Description", "Amount / source value", "Category", "Notes"]} rows={data.ledger.map(e => [e.party || "—", e.description, e.amount === null || e.amount === undefined ? e.raw_amount : money(e.amount), e.category, e.notes || "—"])}/></Panel></>}
      {view === "invoices" && <><Header eyebrow="BILLING" title="Invoices" subtitle="Invoice status connected to KCC client records."/><DataTable headers={["Invoice", "Issued", "Client", "Amount", "Status"]} rows={data.invoices.map(i => [i.invoice_number, date(i.issued_date), i.client_name, money(i.amount), i.status])}/></>}
      {view === "maintenance" && <><Header eyebrow="GROUND CARE" title="Maintenance" subtitle="Repairs, supplies, pitch work, and recurring upkeep."/><div className="kanban">{["To do", "In progress", "Completed"].map(status => <section className="kanban-col" key={status}><div className="kanban-title"><span>{status.toUpperCase()}</span><span>{data.maintenance.filter(t => t.status === status).length}</span></div>{data.maintenance.filter(t => t.status === status).map(t => <article className="task-card" key={t.id}><span className={`status ${t.priority === "Urgent" ? "urgent" : "pending"}`}>{t.priority}</span><strong>{t.title}</strong><p>{t.description}</p><div className="task-meta"><span>{t.category}</span><span>{t.due_date ? date(t.due_date) : "No date"}</span></div></article>)}</section>)}</div></>}
    </div></main>{modal && <RecordModal state={modal} close={() => setModal(null)}/>}</div>;
}

function Header({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle: string; actions?: React.ReactNode }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{actions}</div></div>; }
function Metric({ label, value, note, icon }: { label: string; value: string; note: string; icon: string }) { return <article className="metric-card"><div className="metric-card-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><div className="metric-value">{value}</div><div className="metric-foot">{note}</div></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <article className="panel"><div className="panel-header"><h2>{title}</h2></div>{children}</article>; }
function Schedule({ rows }: { rows: Row[] }) { return <div className="schedule-list">{rows.length ? rows.map(b => <div className="schedule-item" key={b.id}><div className="schedule-time"><strong>{time(b.slot)}</strong><br/>{date(b.booking_date)}</div><div className="schedule-detail"><strong>{b.team_name}</strong><span>{b.captain_name}</span></div><span className={`status ${String(b.status).toLowerCase()}`}>{b.status}</span></div>) : <div className="empty-state">No upcoming bookings.</div>}</div>; }

function TimelineFilter({ value, setValue, from, to, setFrom, setTo }: any) { return <div className="filter-bar"><label>Dashboard period<select value={value} onChange={e => setValue(e.target.value)}><option value="since-launch">Since 01 Oct 2026</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="month">This month</option><option value="custom">Custom dates</option><option value="all">All history</option></select></label>{value === "custom" && <><label>From<input type="date" value={from} onChange={e => setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e => setTo(e.target.value)}/></label></>}</div>; }
function BookingFilters({ status, slot, payment, from, to, setStatus, setSlot, setPayment, setFrom, setTo }: any) { return <div className="filter-bar booking-filter"><label>Status<select value={status} onChange={e => setStatus(e.target.value)}><option>All</option><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select></label><label>Slot<select value={slot} onChange={e => setSlot(e.target.value)}><option>All</option>{SLOTS.map(s => <option key={s}>{s}</option>)}</select></label><label>Payment<select value={payment} onChange={e => setPayment(e.target.value)}><option>All</option><option>Open</option><option>Settled</option></select></label><label>From<input type="date" value={from} onChange={e => setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e => setTo(e.target.value)}/></label><button className="text-button" onClick={() => { setStatus("All"); setSlot("All"); setPayment("All"); setFrom(""); setTo(""); }}>Clear</button></div>; }

function AvailabilityCalendar({ start, setStart, today, bookings, blocked, onBook }: { start: string; setStart: (v: string) => void; today: string; bookings: Row[]; blocked: Row[]; onBook: (d: string, s: string) => void }) {
  const days = Array.from({ length: 14 }, (_, i) => addDays(start, i));
  return <><div className="calendar-toolbar"><button className="secondary-button" onClick={() => setStart(addDays(start, -14))}>← Previous</button><label>Start date<input type="date" value={start} onChange={e => setStart(e.target.value)}/></label><button className="secondary-button" onClick={() => setStart(today)}>Today</button><button className="secondary-button" onClick={() => setStart(addDays(start, 14))}>Next →</button></div><div className="availability-grid">{days.map(day => <article className={`availability-day ${day === today ? "today" : ""}`} key={day}><h3>{new Date(`${day}T12:00:00`).toLocaleDateString("en-IN", { weekday: "short" })}<span>{date(day)}</span></h3>{SLOTS.map(slot => { const booking = bookings.find(b => b.booking_date === day && time(b.slot) === slot && b.status !== "Cancelled"); const closure = blocked.find(b => b.blocked_date === day && (b.slot === "All day" || time(b.slot) === slot)); return <button key={slot} className={`availability-slot ${closure ? "blocked" : booking ? "booked" : "open"}`} disabled={Boolean(closure || booking)} onClick={() => onBook(day, slot)}><strong>{slot}</strong><span>{closure ? `Blocked · ${closure.reason}` : booking ? `${booking.team_name} · Booked` : "Available · Book"}</span></button>; })}</article>)}</div><div className="calendar-legend"><span className="legend-open">Available</span><span className="legend-booked">Booked</span><span className="legend-blocked">Blocked</span></div></>;
}

function BookingTable({ rows, onEdit }: { rows: Row[]; onEdit: (r: Row) => void }) { return <div className="table-wrap"><table><thead><tr><th>Date & slot</th><th>Team / captain</th><th>Quoted</th><th>Advance</th><th>Collected</th><th>Difference</th><th>Booking</th><th>Payment</th><th>Actions</th></tr></thead><tbody>{rows.map(b => <tr key={b.id}><td><strong>{date(b.booking_date)}</strong><br/><small>{time(b.slot)}</small></td><td><strong>{b.team_name}</strong><br/><small>{b.captain_name} · {b.phone || "No phone"}</small></td><td className="amount">{money(b.total_amount)}</td><td className="amount">{money(b.advance_amount)}</td><td className="amount collected">{money(b.collected_amount)}</td><td className={Number(b.balance_amount) ? "amount due" : "amount"}>{Number(b.discount_amount) ? `${money(b.discount_amount)} discount` : money(b.balance_amount)}</td><td><span className={`status ${String(b.status).toLowerCase()}`}>{b.status}</span></td><td><span className={`status ${b.payment_status === "Settled" ? "paid" : "due"}`}>{b.payment_status || "Open"}</span></td><td><div className="row-actions"><button className="row-button edit" onClick={() => onEdit(b)} aria-label="Edit booking">✎</button><form action={deleteBooking}><input type="hidden" name="id" value={b.id}/><button className="row-button" aria-label="Remove booking">×</button></form></div></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state">No bookings match these filters.</div>}</div>; }
function ClientTable({ rows, onEdit }: { rows: Row[]; onEdit: (r: Row) => void }) { return <div className="table-wrap"><table><thead><tr><th>Client</th><th>Team</th><th>Phone</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(c => <tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.team_name}</td><td>{c.phone || "—"}</td><td>{c.email || "—"}</td><td><span className={`status ${c.status === "Active" ? "confirmed" : "cancelled"}`}>{c.status}</span></td><td><button className="row-button edit" onClick={() => onEdit(c)} aria-label="Edit client">✎</button></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state">No clients match the search.</div>}</div>; }
function TournamentGrid({ rows, onEdit }: { rows: Row[]; onEdit: (r: Row) => void }) { return <div className="tournament-grid">{rows.length ? rows.map(t => <article className="tournament-card" key={t.id}><div className="tournament-card-top"><span className={`status ${String(t.status).toLowerCase().replace(" ", "-")}`}>{t.status}</span><div className="row-actions"><button className="row-button edit" onClick={() => onEdit(t)}>✎</button><form action={deleteTournament}><input type="hidden" name="id" value={t.id}/><button className="row-button">×</button></form></div></div><h2>{t.name}</h2><p>{t.format || "Tournament format not added"}</p><dl><div><dt>Dates</dt><dd>{date(t.start_date)}{t.end_date !== t.start_date ? ` – ${date(t.end_date)}` : ""}</dd></div><div><dt>Time</dt><dd>{time(t.start_time)} – {time(t.end_time)}</dd></div><div><dt>Organizer</dt><dd>{t.organizer || "KCC"}</dd></div><div><dt>Contact</dt><dd>{t.contact_phone || "—"}</dd></div></dl>{t.notes && <small>{t.notes}</small>}</article>) : <div className="empty-state panel">No upcoming tournaments added yet.</div>}</div>; }
function DataTable({ headers, rows }: { headers: string[]; rows: any[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((v, j) => <td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length && <div className="empty-state">No records yet.</div>}</div>; }

function RecordModal({ state, close }: { state: NonNullable<ModalState>; close: () => void }) {
  const { type, record, defaults = {} } = state;
  const editing = Boolean(record);
  const action = type === "booking" ? (editing ? updateBooking : createBooking) : type === "client" ? (editing ? updateClient : createClient) : type === "tournament" ? (editing ? updateTournament : createTournament) : blockDate;
  const title = type === "booking" ? `${editing ? "Edit" : "Add"} booking` : type === "client" ? `${editing ? "Edit" : "Add"} client` : type === "tournament" ? `${editing ? "Edit" : "Add"} tournament` : "Block a date";
  const value = (key: string, fallback: any = "") => record?.[key] ?? defaults[key] ?? fallback;
  return <div className="modal"><button className="modal-backdrop" onClick={close} aria-label="Close dialog"/><div className="modal-card"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">KCC ADMIN RECORD</span><h2>{title}</h2><p className="modal-subtitle">Changes are saved to the secure KCC database.</p><form action={async fd => { await action(fd); close(); }}>{record && <input type="hidden" name="id" value={record.id}/>}<div className="form-grid">
    {type === "booking" && <><label>Date<input name="booking_date" type="date" defaultValue={value("booking_date")} required/></label><label>Slot<select name="slot" defaultValue={time(value("slot", "07:00"))}>{SLOTS.map(s => <option key={s}>{s}</option>)}</select></label><label>Team<input name="team_name" defaultValue={value("team_name")} required/></label><label>Captain<input name="captain_name" defaultValue={value("captain_name")} required/></label><label>Phone<input name="phone" defaultValue={value("phone")}/></label><label>Booking status<select name="status" defaultValue={value("status", "Confirmed")}><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select></label><label>Quoted amount<input name="total_amount" type="number" min="0" defaultValue={value("total_amount", 0)} required/></label><label>Advance received<input name="advance_amount" type="number" min="0" defaultValue={value("advance_amount", 0)} required/></label><label>Total collected<input name="collected_amount" type="number" min="0" defaultValue={value("collected_amount", 0)} required/></label><label>Payment state<select name="payment_status" defaultValue={value("payment_status", "Open")}><option>Open</option><option>Settled</option></select><small>Choose Settled to clear a discounted balance.</small></label><label className="full">Notes<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
    {type === "client" && <><label>Name<input name="name" defaultValue={value("name")} required/></label><label>Team<input name="team_name" defaultValue={value("team_name")} required/></label><label>Phone<input name="phone" defaultValue={value("phone")}/></label><label>Email<input name="email" type="email" defaultValue={value("email")}/></label><label>Status<select name="status" defaultValue={value("status", "Active")}><option>Active</option><option>Inactive</option></select></label><label className="full">Notes<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
    {type === "block" && <><label>Date<input name="blocked_date" type="date" defaultValue={value("blocked_date")} required/></label><label>Slot<select name="slot" defaultValue={value("slot", "All day")}><option>All day</option>{SLOTS.map(s => <option key={s}>{s}</option>)}</select></label><label className="full">Reason<input name="reason" defaultValue={value("reason")} required/></label></>}
    {type === "tournament" && <><label className="full">Tournament name<input name="name" defaultValue={value("name")} required/></label><label>Start date<input name="start_date" type="date" defaultValue={value("start_date")} required/></label><label>End date<input name="end_date" type="date" defaultValue={value("end_date")} required/></label><label>Start time<input name="start_time" type="time" defaultValue={time(value("start_time", "07:00"))} required/></label><label>End time<input name="end_time" type="time" defaultValue={time(value("end_time", "18:00"))} required/></label><label>Format<input name="format" placeholder="League, knockout, T20…" defaultValue={value("format")}/></label><label>Status<select name="status" defaultValue={value("status", "Upcoming")}><option>Upcoming</option><option>In progress</option><option>Completed</option><option>Cancelled</option></select></label><label>Organizer<input name="organizer" defaultValue={value("organizer")}/></label><label>Contact phone<input name="contact_phone" defaultValue={value("contact_phone")}/></label><label className="full">Details<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
  </div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button">{editing ? "Save changes" : "Save securely"}</button></div></form></div></div>;
}
