"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import {
  blockDate, createBooking, createClient, createExpense, createMaintenanceTask, createTournament, deleteBooking, deleteExpense, deletePayment, deleteTournament,
  recordPayment, sendPaymentRequest, signOut, updateBooking, updateClient, updateExpense, updateMaintenanceTask, updateTournament,
} from "./actions";

type Row = Record<string, any>;
type View = "dashboard" | "availability" | "bookings" | "clients" | "tournaments" | "payments" | "expenses" | "maintenance";
type ModalState = { type: "booking" | "client" | "block" | "tournament" | "maintenance" | "payment" | "paymentRequest" | "expense"; record?: Row; defaults?: Row } | null;
type Data = { bookings: Row[]; clients: Row[]; expenses: Row[]; maintenance: Row[]; blocked: Row[]; collections: Row[]; ledger: Row[]; tournaments: Row[]; payments: Row[]; paymentRequests: Row[]; invoices: Row[]; notifications: Row[] };

const LAUNCH_DATE = "2026-10-01";
const SLOTS = ["07:00", "10:30", "14:00"];
const money = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n || 0);
const date = (d: string | null) => d ? new Date(`${d}T12:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
const iso = (value: Date) => value.toISOString().slice(0, 10);
const addDays = (value: string, days: number) => { const d = new Date(`${value}T12:00:00`); d.setDate(d.getDate() + days); return iso(d); };
const time = (value: string | null) => value ? String(value).slice(0, 5) : "—";
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }) : "—";
const dateTimeInput = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";
const chicagoDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-CA", { timeZone: "America/Chicago", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(value)) : "";

export function DashboardClient({ data, today }: { data: Data; today: string }) {
  const [view, setView] = useState<View>("dashboard");
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [modal, setModal] = useState<ModalState>(null);
  const [search, setSearch] = useState("");
  const [timeline, setTimeline] = useState("month");
  const [bookingStatus, setBookingStatus] = useState("All");
  const [bookingSlot, setBookingSlot] = useState("All");
  const [paymentStatus, setPaymentStatus] = useState("All");
  const [bookingFrom, setBookingFrom] = useState("");
  const [bookingTo, setBookingTo] = useState("");
  const [calendarStart, setCalendarStart] = useState(today);

  const range = useMemo(() => {
    if (timeline === "day") return { from: today, to: today };
    if (timeline === "7d") return { from: addDays(today, -6), to: today };
    const [year, month] = today.split("-").map(Number);
    if (timeline === "lastMonth") return { from: iso(new Date(Date.UTC(year, month - 2, 1))), to: iso(new Date(Date.UTC(year, month - 1, 0))) };
    if (timeline === "all") return { from: LAUNCH_DATE, to: today };
    return { from: `${today.slice(0, 8)}01`, to: iso(new Date(Date.UTC(year, month, 0))) };
  }, [timeline, today]);

  const inRange = (value: string | null) => Boolean(value && (!range.from || value >= range.from) && (!range.to || value <= range.to));
  const dashboardBookings = data.bookings.filter(b => inRange(b.booking_date));
  const dashboardExpenses = data.expenses.filter(e => inRange(e.expense_date));
  const totals = useMemo(() => {
    const paidByBooking = new Map<string, number>();
    for (const payment of data.payments.filter(payment => payment.status === "Paid")) {
      paidByBooking.set(payment.booking_id, (paidByBooking.get(payment.booking_id) || 0) + Number(payment.amount || 0));
    }
    const importedCollections = dashboardBookings.reduce((sum, booking) => sum + Math.max(Number(booking.collected_amount || 0) - (paidByBooking.get(booking.id) || 0), 0), 0);
    const recordedCollections = data.payments.filter(payment => payment.status === "Paid" && inRange(chicagoDate(payment.paid_at || payment.created_at))).reduce((sum, payment) => sum + Number(payment.amount || 0), 0);
    const income = importedCollections + recordedCollections;
    const expenses = dashboardExpenses.reduce((sum, expense) => sum + Number(expense.amount || 0), 0);
    return { income, balance: dashboardBookings.reduce((sum, booking) => sum + Number(booking.balance_amount || 0), 0), expenses, net: income - expenses };
  }, [data.payments, dashboardBookings, dashboardExpenses, range]);

  const filteredBookings = useMemo(() => data.bookings
    .filter(b => Object.values(b).join(" ").toLowerCase().includes(search.toLowerCase()))
    .filter(b => bookingStatus === "All" || b.status === bookingStatus)
    .filter(b => bookingSlot === "All" || time(b.slot) === bookingSlot)
    .filter(b => paymentStatus === "All" || b.payment_status === paymentStatus)
    .filter(b => !bookingFrom || b.booking_date >= bookingFrom)
    .filter(b => !bookingTo || b.booking_date <= bookingTo)
    .sort((a, b) => `${b.booking_date}${b.slot}`.localeCompare(`${a.booking_date}${a.slot}`)),
  [data.bookings, search, bookingStatus, bookingSlot, paymentStatus, bookingFrom, bookingTo]);

  const upcoming = data.bookings.filter(b => b.booking_date >= today && b.status !== "Cancelled")
    .sort((a, b) => `${a.booking_date}${a.slot}`.localeCompare(`${b.booking_date}${b.slot}`)).slice(0, 7);
  const paidTotal = data.payments.filter(p => p.status === "Paid").reduce((sum, p) => sum + Number(p.amount || 0), 0);
  const pendingTotal = data.bookings.filter(b => b.status !== "Cancelled").reduce((sum, b) => sum + Number(b.balance_amount || 0), 0);
  const nav: [View, string, string][] = [
    ["dashboard", "⌂", "Overview"], ["availability", "▦", "Slot calendar"], ["bookings", "◫", "Bookings"],
    ["clients", "♙", "Clients"], ["tournaments", "♛", "Tournaments"], ["payments", "₹", "Payments"],
    ["expenses", "−", "Expenses"], ["maintenance", "◇", "Maintenance"],
  ];

  return <div className="app-shell">
    {mobileMenuOpen && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMobileMenuOpen(false)}/>}
    <aside className={`sidebar ${mobileMenuOpen ? "open" : ""}`}><div className="brand"><Image src="/kcc-logo.jpeg" alt="KCC" width={50} height={50}/><div><strong>KCC</strong><span>Ground Admin</span></div><button className="sidebar-close" aria-label="Close navigation" onClick={() => setMobileMenuOpen(false)}>×</button></div>
      <nav>{nav.map(([id, icon, label]) => <button key={id} className={`nav-item ${view === id ? "active" : ""}`} onClick={() => { setView(id); setMobileMenuOpen(false); }}><span className="nav-icon">{icon}</span>{label}{id === "bookings" && <span className="nav-count">{data.bookings.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="season-card"><span>SECURE ACCESS</span><strong>KCC administrator</strong><div className="progress"><i style={{ width: "100%" }}/></div><small>Authenticated database session</small></div><form action={signOut}><button className="profile-card"><span className="avatar">KCC</span><span><strong>KCC Admin</strong><small>Administrator</small></span><span>↪</span></button></form></div>
    </aside>
    <main className="main"><header className="topbar"><button className="menu-toggle" aria-label="Open navigation" aria-expanded={mobileMenuOpen} onClick={() => setMobileMenuOpen(true)}>☰</button>{(["bookings", "clients", "expenses"] as View[]).includes(view) ? <div className="search"><span>⌕</span><input placeholder={`Search ${view}…`} value={search} onChange={e => setSearch(e.target.value)}/></div> : <div className="topbar-title">KCC Ground Admin</div>}<div className="top-actions"><button className="date-chip"><span>Secure session</span><strong>KCC Ground Admin</strong></button></div></header><div className="content">
      {view === "dashboard" && <><Header eyebrow="OVERVIEW" title="KCC at a glance" subtitle="What came in, what went out, and what is coming next." actions={<button className="primary-button" onClick={() => setModal({ type: "booking" })}>＋ New booking</button>}/><TimelineFilter value={timeline} setValue={setTimeline}/><div className="metric-grid simple-metrics"><Metric label="MONEY COLLECTED" value={money(totals.income)} note="Received during this period" icon="₹"/><Metric label="EXPENSES" value={money(totals.expenses)} note="Ground and operating spend" icon="−"/><Metric label="NET EARNINGS" value={money(totals.net)} note="Collected minus expenses" icon="="/><Metric label="STILL TO COLLECT" value={money(totals.balance)} note="Open booking balances" icon="◷"/></div><div className="dashboard-grid simple-dashboard"><Panel title="Upcoming bookings"><Schedule rows={upcoming}/></Panel><Panel title="Recent expenses"><ExpenseMiniList rows={dashboardExpenses.slice(0, 6)} onViewAll={() => setView("expenses")}/></Panel></div><div className="simple-actions"><button onClick={() => setModal({ type: "expense", defaults: { expense_date: today } })}>＋ Add expense</button><button onClick={() => setView("availability")}>▦ Check slots</button><button onClick={() => setModal({ type: "block" })}>＋ Block date</button></div></>}
      {view === "availability" && <><Header eyebrow="GROUND CALENDAR" title="Slot availability" subtitle="Booked, blocked, and open ground slots at a glance." actions={<><button className="secondary-button" onClick={() => setModal({ type: "block" })}>＋ Block date</button><button className="primary-button" onClick={() => setModal({ type: "booking" })}>＋ New booking</button></>}/><AvailabilityCalendar start={calendarStart} setStart={setCalendarStart} today={today} bookings={data.bookings} blocked={data.blocked} onBook={(bookingDate, slot) => setModal({ type: "booking", defaults: { booking_date: bookingDate, slot } })}/></>}
      {view === "bookings" && <><Header eyebrow="SCHEDULE" title="Bookings" subtitle="Newest bookings appear first. Edit details, request payment, or record money received." actions={<button className="primary-button" onClick={() => setModal({ type: "booking" })}>＋ New booking</button>}/><BookingFilters status={bookingStatus} slot={bookingSlot} payment={paymentStatus} from={bookingFrom} to={bookingTo} setStatus={setBookingStatus} setSlot={setBookingSlot} setPayment={setPaymentStatus} setFrom={setBookingFrom} setTo={setBookingTo}/><BookingTable rows={filteredBookings} onEdit={record => setModal({ type: "booking", record })} onPay={booking => setModal({ type: "payment", defaults: { booking_id: booking.id, amount: booking.balance_amount, payment_type: Number(booking.collected_amount || 0) > 0 ? "Balance" : "Advance" } })} onRequest={record => setModal({ type: "paymentRequest", record })}/></>}
      {view === "clients" && <><Header eyebrow="CLIENT CRM" title="Clients" subtitle="Select Edit to update contact, team, status, or notes." actions={<button className="primary-button" onClick={() => setModal({ type: "client" })}>＋ Add client</button>}/><ClientTable rows={data.clients.filter(c => Object.values(c).join(" ").toLowerCase().includes(search.toLowerCase()))} onEdit={record => setModal({ type: "client", record })}/></>}
      {view === "tournaments" && <><Header eyebrow="TOURNAMENT DESK" title="Tournaments" subtitle="Upcoming tournament dates, timings, format, organizer, and contact details." actions={<button className="primary-button" onClick={() => setModal({ type: "tournament" })}>＋ Add tournament</button>}/><TournamentGrid rows={data.tournaments} onEdit={record => setModal({ type: "tournament", record })}/></>}
      {view === "payments" && <><Header eyebrow="FINANCE" title="Payments" subtitle="Add cash, UPI, bank, or payment-link collections manually. Delete a mistaken entry from payment history." actions={<button className="primary-button" onClick={() => setModal({ type: "payment" })}>＋ Add payment</button>}/><ManualPaymentPanel rows={data.bookings.filter(b => b.status !== "Cancelled" && Number(b.balance_amount) > 0)} onPay={booking => setModal({ type: "payment", defaults: { booking_id: booking.id, amount: booking.balance_amount, payment_type: Number(booking.collected_amount || 0) > 0 ? "Balance" : "Advance" } })}/><div className="metric-grid finance-metrics"><Metric label="RECORDED PAYMENTS" value={money(paidTotal)} note="Payments entered through this system" icon="₹"/><Metric label="BALANCE DUE" value={money(pendingTotal)} note="Across active bookings" icon="◷"/><Metric label="OPEN REQUESTS" value={String(data.paymentRequests.filter(r => r.status === "Open").length)} note="UPI requests awaiting payment" icon="↗"/><Metric label="RECEIPTS" value={String(data.invoices.length)} note="Generated after full payment" icon="✓"/></div><Panel title="Payment history"><PaymentTable payments={data.payments} bookings={data.bookings} invoices={data.invoices}/></Panel><Panel title="Open payment requests"><RequestTable rows={data.paymentRequests} bookings={data.bookings}/></Panel><Panel title="Email activity"><NotificationTable rows={data.notifications} bookings={data.bookings}/></Panel><details className="legacy-panel"><summary>Imported finance history</summary><Panel title="Workbook collections"><DataTable headers={["Date", "Client / source", "Description", "Amount"]} rows={data.collections.map(c => [date(c.collection_date), c.client_name || c.category, c.description, money(c.amount)])}/></Panel></details></>}
      {view === "expenses" && <><Header eyebrow="GROUND SPEND" title="Expenses" subtitle="Record maintenance, supplies, equipment, utilities, and other ground costs." actions={<button className="primary-button" onClick={() => setModal({ type: "expense", defaults: { expense_date: today } })}>＋ Add expense</button>}/><div className="metric-grid expense-metrics"><Metric label="TOTAL SPENT" value={money(data.expenses.reduce((sum, row) => sum + Number(row.amount || 0), 0))} note="All recorded expenses" icon="₹"/><Metric label="THIS MONTH" value={money(data.expenses.filter(row => row.expense_date?.slice(0, 7) === today.slice(0, 7)).reduce((sum, row) => sum + Number(row.amount || 0), 0))} note="Current month spend" icon="◷"/><Metric label="ENTRIES" value={String(data.expenses.length)} note="Expense records" icon="#"/></div><ExpenseTable rows={data.expenses.filter(row => Object.values(row).join(" ").toLowerCase().includes(search.toLowerCase()))} onEdit={record => setModal({ type: "expense", record })}/></>}
      {view === "maintenance" && <><Header eyebrow="GROUND CARE" title="Maintenance" subtitle="Add and update repairs, supplies, pitch work, and recurring upkeep." actions={<button className="primary-button" onClick={() => setModal({ type: "maintenance" })}>＋ Add task</button>}/><div className="kanban">{["To do", "In progress", "Completed"].map(status => <section className="kanban-col" key={status}><div className="kanban-title"><span>{status.toUpperCase()}</span><span>{data.maintenance.filter(t => t.status === status).length}</span></div>{data.maintenance.filter(t => t.status === status).map(t => <article className="task-card" key={t.id}><div className="task-card-top"><span className={`status ${t.priority === "Urgent" ? "urgent" : "pending"}`}>{t.priority}</span><button className="row-button edit" onClick={() => setModal({ type: "maintenance", record: t })} aria-label={`Edit ${t.title}`}>✎</button></div><strong>{t.title}</strong><p>{t.description || "No description added."}</p><div className="task-meta"><span>{t.category}</span><span>{t.due_date ? date(t.due_date) : "No due date"}</span></div></article>)}</section>)}</div></>}
    </div></main>{modal && <RecordModal state={modal} data={data} close={() => setModal(null)}/>}</div>;
}

function Header({ eyebrow, title, subtitle, actions }: { eyebrow: string; title: string; subtitle: string; actions?: React.ReactNode }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{actions}</div></div>; }
function Metric({ label, value, note, icon }: { label: string; value: string; note: string; icon: string }) { return <article className="metric-card"><div className="metric-card-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><div className="metric-value">{value}</div><div className="metric-foot">{note}</div></article>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <article className="panel"><div className="panel-header"><h2>{title}</h2></div>{children}</article>; }
function Schedule({ rows }: { rows: Row[] }) { return <div className="schedule-list">{rows.length ? rows.map(b => <div className="schedule-item" key={b.id}><div className="schedule-time"><strong>{time(b.slot)}</strong><br/>{date(b.booking_date)}</div><div className="schedule-detail"><strong>{b.team_name}</strong><span>{b.captain_name}</span></div><span className={`status ${String(b.status).toLowerCase()}`}>{b.status}</span></div>) : <div className="empty-state">No upcoming bookings.</div>}</div>; }
function ExpenseMiniList({ rows, onViewAll }: { rows: Row[]; onViewAll: () => void }) { return <div className="expense-mini-list">{rows.length ? rows.map(row => <div className="expense-mini-item" key={row.id}><span><strong>{row.item}</strong><small>{row.category} · {date(row.expense_date)}</small></span><b>{money(row.amount)}</b></div>) : <div className="empty-state compact">No expenses in this period.</div>}<button className="text-button expense-view-all" onClick={onViewAll}>View all expenses →</button></div>; }

function TimelineFilter({ value, setValue }: { value: string; setValue: (value: string) => void }) { return <div className="filter-bar"><label>Dashboard period<select value={value} onChange={e => setValue(e.target.value)}><option value="day">Today</option><option value="7d">Last 7 days</option><option value="month">This month</option><option value="lastMonth">Last month</option><option value="all">All time</option></select></label></div>; }
function BookingFilters({ status, slot, payment, from, to, setStatus, setSlot, setPayment, setFrom, setTo }: any) { return <div className="filter-bar booking-filter"><label>Status<select value={status} onChange={e => setStatus(e.target.value)}><option>All</option><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select></label><label>Slot<select value={slot} onChange={e => setSlot(e.target.value)}><option>All</option>{SLOTS.map(s => <option key={s}>{s}</option>)}</select></label><label>Payment<select value={payment} onChange={e => setPayment(e.target.value)}><option>All</option><option>Open</option><option>Settled</option></select></label><label>From<input type="date" min={LAUNCH_DATE} value={from} onChange={e => setFrom(e.target.value)}/></label><label>To<input type="date" min={LAUNCH_DATE} value={to} onChange={e => setTo(e.target.value)}/></label><button className="text-button" onClick={() => { setStatus("All"); setSlot("All"); setPayment("All"); setFrom(""); setTo(""); }}>Clear</button></div>; }

function AvailabilityCalendar({ start, setStart, today, bookings, blocked, onBook }: { start: string; setStart: (v: string) => void; today: string; bookings: Row[]; blocked: Row[]; onBook: (d: string, s: string) => void }) {
  const days = Array.from({ length: 14 }, (_, i) => addDays(start, i));
  return <><div className="calendar-toolbar"><button className="secondary-button" onClick={() => setStart(addDays(start, -14))}>← Previous</button><label>Start date<input type="date" value={start} onChange={e => setStart(e.target.value)}/></label><button className="secondary-button" onClick={() => setStart(today)}>Today</button><button className="secondary-button" onClick={() => setStart(addDays(start, 14))}>Next →</button></div><div className="availability-grid">{days.map(day => <article className={`availability-day ${day === today ? "today" : ""}`} key={day}><h3>{new Date(`${day}T12:00:00`).toLocaleDateString("en-IN", { weekday: "short" })}<span>{date(day)}</span></h3>{SLOTS.map(slot => { const booking = bookings.find(b => b.booking_date === day && time(b.slot) === slot && b.status !== "Cancelled"); const closure = blocked.find(b => b.blocked_date === day && (b.slot === "All day" || time(b.slot) === slot)); return <button key={slot} className={`availability-slot ${closure ? "blocked" : booking ? "booked" : "open"}`} disabled={Boolean(closure || booking)} onClick={() => onBook(day, slot)}><strong>{slot}</strong><span>{closure ? `Blocked · ${closure.reason}` : booking ? `${booking.team_name} · Booked` : "Available · Book"}</span></button>; })}</article>)}</div><div className="calendar-legend"><span className="legend-open">Available</span><span className="legend-booked">Booked</span><span className="legend-blocked">Blocked</span></div></>;
}

function BookingTable({ rows, onEdit, onPay, onRequest }: { rows: Row[]; onEdit: (r: Row) => void; onPay: (r: Row) => void; onRequest: (r: Row) => void }) { return <div className="table-wrap mobile-card-table"><table><thead><tr><th>Date & slot</th><th>Team / captain</th><th>Total</th><th>Advance requested</th><th>Collected</th><th>Balance</th><th>Booking</th><th>Actions</th></tr></thead><tbody>{rows.map(b => <tr key={b.id}><td data-label="Date & slot"><strong>{date(b.booking_date)}</strong><br/><small>{time(b.slot)}</small></td><td data-label="Team / captain"><strong>{b.team_name}</strong><br/><small>{b.captain_name} · {b.phone || "No phone"}<br/>{b.client_email || "No email"}</small></td><td data-label="Total" className="amount">{money(b.total_amount)}</td><td data-label="Advance requested" className="amount">{money(b.advance_amount)}</td><td data-label="Collected" className="amount collected">{money(b.collected_amount)}</td><td data-label="Balance" className="amount">{money(b.balance_amount)}</td><td data-label="Booking"><span className={`status ${String(b.status).toLowerCase()}`}>{b.status}</span><br/><span className={`status ${b.payment_status === "Settled" ? "paid" : "due"}`}>{b.payment_status || "Open"}</span></td><td data-label="Actions"><div className="row-actions"><button className="row-button payment" onClick={() => onPay(b)} aria-label="Record payment">₹</button><button className="row-button request" onClick={() => onRequest(b)} aria-label="Send payment request">↗</button><button className="row-button edit" onClick={() => onEdit(b)} aria-label="Edit booking">✎</button><form action={deleteBooking}><input type="hidden" name="id" value={b.id}/><button className="row-button" aria-label="Remove booking">×</button></form></div></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state">No bookings match these filters.</div>}</div>; }
function ClientTable({ rows, onEdit }: { rows: Row[]; onEdit: (r: Row) => void }) { return <div className="table-wrap mobile-card-table"><table><thead><tr><th>Client</th><th>Team</th><th>Phone</th><th>Email</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(c => <tr key={c.id}><td data-label="Client"><strong>{c.name}</strong></td><td data-label="Team">{c.team_name}</td><td data-label="Phone">{c.phone || "—"}</td><td data-label="Email">{c.email || "—"}</td><td data-label="Status"><span className={`status ${c.status === "Active" ? "confirmed" : "cancelled"}`}>{c.status}</span></td><td data-label="Actions"><button className="row-button edit" onClick={() => onEdit(c)} aria-label="Edit client">✎</button></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state">No clients match the search.</div>}</div>; }
function TournamentGrid({ rows, onEdit }: { rows: Row[]; onEdit: (r: Row) => void }) { return <div className="tournament-grid">{rows.length ? rows.map(t => <article className="tournament-card" key={t.id}><div className="tournament-card-top"><span className={`status ${String(t.status).toLowerCase().replace(" ", "-")}`}>{t.status}</span><div className="row-actions"><button className="row-button edit" onClick={() => onEdit(t)}>✎</button><form action={deleteTournament}><input type="hidden" name="id" value={t.id}/><button className="row-button">×</button></form></div></div><h2>{t.name}</h2><p>{t.format || "Tournament format not added"}</p><dl><div><dt>Dates</dt><dd>{date(t.start_date)}{t.end_date !== t.start_date ? ` – ${date(t.end_date)}` : ""}</dd></div><div><dt>Time</dt><dd>{time(t.start_time)} – {time(t.end_time)}</dd></div><div><dt>Organizer</dt><dd>{t.organizer || "KCC"}</dd></div><div><dt>Contact</dt><dd>{t.contact_phone || "—"}</dd></div></dl>{t.notes && <small>{t.notes}</small>}</article>) : <div className="empty-state panel">No upcoming tournaments added yet.</div>}</div>; }
function ManualPaymentPanel({ rows, onPay }: { rows: Row[]; onPay: (r: Row) => void }) { return <section className="manual-payment-panel"><div><span className="eyebrow">MANUAL PAYMENT ENTRY</span><h2>Add a payment received outside the app</h2><p>Select a booking after receiving UPI, cash, or bank payment. The balance updates immediately, and full payment creates a Payment Receipt.</p></div>{rows.length ? <div className="manual-payment-list">{rows.slice(0, 5).map(b => <button key={b.id} onClick={() => onPay(b)}><span><strong>{b.team_name}</strong><small>{date(b.booking_date)} · {b.captain_name}</small></span><span><small>Balance</small><strong>{money(b.balance_amount)}</strong></span><b>＋ Add payment</b></button>)}</div> : <div className="empty-state compact">No active booking balances.</div>}</section>; }
function ExpenseTable({ rows, onEdit }: { rows: Row[]; onEdit: (record: Row) => void }) { return <div className="table-wrap mobile-card-table"><table><thead><tr><th>Date</th><th>Expense</th><th>Category</th><th>Details</th><th>Status</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td data-label="Date">{date(row.expense_date)}</td><td data-label="Expense"><strong>{row.item}</strong></td><td data-label="Category">{row.category}</td><td data-label="Details">{row.notes || "—"}</td><td data-label="Status"><span className={`status ${row.status === "Paid" ? "paid" : "pending"}`}>{row.status}</span></td><td data-label="Amount" className="amount">{money(row.amount)}</td><td data-label="Actions"><div className="row-actions"><button className="row-button edit" onClick={() => onEdit(row)} aria-label={`Edit ${row.item}`}>✎</button><form action={deleteExpense} onSubmit={event => { if (!window.confirm(`Delete the expense “${row.item}”?`)) event.preventDefault(); }}><input type="hidden" name="id" value={row.id}/><button className="row-button" aria-label={`Delete ${row.item}`}>×</button></form></div></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state">No expenses recorded yet. Select Add expense to create the first one.</div>}</div>; }
function PaymentTable({ payments, bookings, invoices }: { payments: Row[]; bookings: Row[]; invoices: Row[] }) { return <div className="table-wrap mobile-card-table"><table><thead><tr><th>Paid</th><th>Booking</th><th>Type / method</th><th>Reference</th><th>Amount</th><th>Receipt</th><th>Action</th></tr></thead><tbody>{payments.map(p => { const b = bookings.find(row => row.id === p.booking_id); const invoice = invoices.find(row => row.booking_id === p.booking_id && row.status === "Paid"); return <tr key={p.id}><td data-label="Paid">{dateTime(p.paid_at || p.created_at)}</td><td data-label="Booking"><strong>{b?.team_name || "Booking"}</strong><br/><small>{b ? `${date(b.booking_date)} · ${time(b.slot)}` : p.booking_id}</small></td><td data-label="Type / method">{p.payment_type}<br/><small>{p.method}</small></td><td data-label="Reference">{p.reference || "Recorded manually"}</td><td data-label="Amount" className="amount collected">{money(p.amount)}</td><td data-label="Receipt">{invoice ? <a className="table-link" href={`/api/invoices/${invoice.public_token}`} target="_blank">Download PDF</a> : <span className="status pending">Part payment</span>}</td><td data-label="Action"><form action={deletePayment} onSubmit={event => { if (!window.confirm(`Delete this ${money(p.amount)} payment? The booking balance will be recalculated.`)) event.preventDefault(); }}><input type="hidden" name="id" value={p.id}/><button className="row-button" aria-label={`Delete ${money(p.amount)} payment`}>× Delete</button></form></td></tr>; })}</tbody></table>{!payments.length && <div className="empty-state">No booking-linked payments yet. Select Add payment to record the first one.</div>}</div>; }
function RequestTable({ rows, bookings }: { rows: Row[]; bookings: Row[] }) { return <div className="table-wrap mobile-card-table"><table><thead><tr><th>Created</th><th>Booking</th><th>Amount</th><th>Status</th><th>Customer view</th></tr></thead><tbody>{rows.map(r => { const b = bookings.find(row => row.id === r.booking_id); return <tr key={r.id}><td data-label="Created">{dateTime(r.created_at)}</td><td data-label="Booking"><strong>{b?.team_name || "Booking"}</strong><br/><small>{b?.client_email || "Manual-share link"}</small></td><td data-label="Amount" className="amount">{money(r.amount)}</td><td data-label="Status"><span className={`status ${r.status === "Paid" ? "paid" : "pending"}`}>{r.status}</span></td><td data-label="Customer view"><a className="table-link" href={`/pay/${r.public_token}`} target="_blank">Open payment page</a></td></tr>; })}</tbody></table>{!rows.length && <div className="empty-state">No payment requests yet. Create one from a booking when needed.</div>}</div>; }
function NotificationTable({ rows, bookings }: { rows: Row[]; bookings: Row[] }) { return <div className="table-wrap mobile-card-table"><table><thead><tr><th>Time</th><th>Client</th><th>Message</th><th>Status</th></tr></thead><tbody>{rows.map(n => { const b = bookings.find(row => row.id === n.booking_id); return <tr key={n.id}><td data-label="Time">{dateTime(n.created_at)}</td><td data-label="Client"><strong>{b?.captain_name || "KCC client"}</strong><br/><small>{n.recipient}</small></td><td data-label="Message">{n.notification_type}<br/><small>{n.subject}</small></td><td data-label="Status"><span className={`status ${n.status === "Sent" ? "paid" : n.status === "Failed" ? "cancelled" : "pending"}`}>{n.status}</span>{n.error_message && <small className="status-note">{n.error_message}</small>}</td></tr>; })}</tbody></table>{!rows.length && <div className="empty-state">Email previews and delivery results will appear here.</div>}</div>; }
function DataTable({ headers, rows }: { headers: string[]; rows: any[][] }) { return <div className="table-wrap"><table><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((v, j) => <td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length && <div className="empty-state">No records yet.</div>}</div>; }

function RecordModal({ state, data, close }: { state: NonNullable<ModalState>; data: Data; close: () => void }) {
  const { type, record, defaults = {} } = state;
  const editing = Boolean(record);
  const [selectedClientId, setSelectedClientId] = useState(String(record?.client_id || ""));
  const selectedClient = data.clients.find(client => client.id === selectedClientId);
  const action = type === "booking" ? (editing ? updateBooking : createBooking) : type === "client" ? (editing ? updateClient : createClient) : type === "tournament" ? (editing ? updateTournament : createTournament) : type === "maintenance" ? (editing ? updateMaintenanceTask : createMaintenanceTask) : type === "expense" ? (editing ? updateExpense : createExpense) : type === "payment" ? recordPayment : type === "paymentRequest" ? sendPaymentRequest : blockDate;
  const title = type === "booking" ? `${editing ? "Edit" : "Add"} booking` : type === "client" ? `${editing ? "Edit" : "Add"} client` : type === "tournament" ? `${editing ? "Edit" : "Add"} tournament` : type === "maintenance" ? `${editing ? "Edit" : "Add"} maintenance task` : type === "expense" ? `${editing ? "Edit" : "Add"} expense` : type === "payment" ? "Add payment" : type === "paymentRequest" ? "Create payment request" : "Block a date";
  const value = (key: string, fallback: any = "") => record?.[key] ?? defaults[key] ?? fallback;
  const showId = record && ["booking", "client", "tournament", "maintenance", "expense"].includes(type);
  const selectedPaymentBooking = type === "payment" ? data.bookings.find(b => b.id === value("booking_id")) : undefined;
  const paymentMaximum = selectedPaymentBooking ? Number(selectedPaymentBooking.balance_amount || 0) + (editing ? Number(value("amount", 0)) : 0) : undefined;
  return <div className="modal"><button className="modal-backdrop" onClick={close} aria-label="Close dialog"/><div className="modal-card"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">KCC ADMIN RECORD</span><h2>{title}</h2><p className="modal-subtitle">Changes are saved to the secure KCC database.</p><form action={async fd => { await action(fd); close(); }}>{showId && <input type="hidden" name="id" value={record?.id}/>}<div className="form-grid">
    {type === "booking" && <><input type="hidden" name="collected_amount" value={value("collected_amount", 0)}/><label className="full">Use an existing client <span className="optional-label">Optional</span><select name="client_id" value={selectedClientId} onChange={event => setSelectedClientId(event.target.value)}><option value="">Enter client details manually</option>{data.clients.filter(client => client.status === "Active" || client.id === record?.client_id).sort((a, b) => String(a.name).localeCompare(String(b.name))).map(client => <option key={client.id} value={client.id}>{client.name} · {client.team_name}</option>)}</select><small>Selecting a client fills the contact details below. You can still adjust them for this booking.</small></label><label>Date<input name="booking_date" type="date" min={LAUNCH_DATE} defaultValue={value("booking_date")} required/></label><label>Slot<select name="slot" defaultValue={time(value("slot", "07:00"))}>{SLOTS.map(s => <option key={s}>{s}</option>)}</select></label><label>Team<input key={`team-${selectedClientId}`} name="team_name" defaultValue={selectedClient?.team_name ?? value("team_name")} required/></label><label>Captain<input key={`captain-${selectedClientId}`} name="captain_name" defaultValue={selectedClient?.name ?? value("captain_name")} required/></label><label>Client email <span className="optional-label">Optional</span><input key={`email-${selectedClientId}`} name="client_email" type="email" inputMode="email" autoComplete="email" placeholder="client@gmail.com" defaultValue={selectedClient?.email ?? value("client_email")}/><small>Add it only when you want KCC to email the client.</small></label><label>Phone<input key={`phone-${selectedClientId}`} name="phone" inputMode="tel" autoComplete="tel" defaultValue={selectedClient?.phone ?? value("phone")}/></label><label>Booking status<select name="status" defaultValue={value("status", "Confirmed")}><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select></label><label>Total amount<input name="total_amount" type="number" min="0" defaultValue={value("total_amount", 0)} required/></label><label>Advance requested<input name="advance_amount" type="number" min="0" defaultValue={value("advance_amount", 0)} required/><small>Used when a payment request is created.</small></label>{!editing && <label className="full communication-choice">After saving<select name="communication_action" defaultValue="save"><option value="save">Save booking only — do not contact client</option><option value="send">Save and email confirmation + payment request</option></select><small>Email is required only for the second option. You can create a payment request later from Bookings.</small></label>}<label className="full">Notes<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
    {type === "client" && <><label>Name<input name="name" defaultValue={value("name")} required/></label><label>Team<input name="team_name" defaultValue={value("team_name")} required/></label><label>Phone<input name="phone" defaultValue={value("phone")}/></label><label>Email<input name="email" type="email" defaultValue={value("email")}/></label><label>Status<select name="status" defaultValue={value("status", "Active")}><option>Active</option><option>Inactive</option></select></label><label className="full">Notes<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
    {type === "block" && <><label>Date<input name="blocked_date" type="date" min={LAUNCH_DATE} defaultValue={value("blocked_date")} required/></label><label>Slot<select name="slot" defaultValue={value("slot", "All day")}><option>All day</option>{SLOTS.map(s => <option key={s}>{s}</option>)}</select></label><label className="full">Reason<input name="reason" defaultValue={value("reason")} required/></label></>}
    {type === "tournament" && <><label className="full">Tournament name<input name="name" defaultValue={value("name")} required/></label><label>Start date<input name="start_date" type="date" defaultValue={value("start_date")} required/></label><label>End date<input name="end_date" type="date" defaultValue={value("end_date")} required/></label><label>Start time<input name="start_time" type="time" defaultValue={time(value("start_time", "07:00"))} required/></label><label>End time<input name="end_time" type="time" defaultValue={time(value("end_time", "18:00"))} required/></label><label>Format<input name="format" placeholder="League, knockout, T20…" defaultValue={value("format")}/></label><label>Status<select name="status" defaultValue={value("status", "Upcoming")}><option>Upcoming</option><option>In progress</option><option>Completed</option><option>Cancelled</option></select></label><label>Organizer<input name="organizer" defaultValue={value("organizer")}/></label><label>Contact phone<input name="contact_phone" defaultValue={value("contact_phone")}/></label><label className="full">Details<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
    {type === "maintenance" && <><label className="full">Task title<input name="title" defaultValue={value("title")} required/></label><label>Category<input name="category" placeholder="Ground care, electrical…" defaultValue={value("category")} required/></label><label>Due date<input name="due_date" type="date" defaultValue={value("due_date")}/></label><label>Priority<select name="priority" defaultValue={value("priority", "Routine")}><option>Routine</option><option>Urgent</option></select></label><label>Status<select name="status" defaultValue={value("status", "To do")}><option>To do</option><option>In progress</option><option>Completed</option></select></label><label className="full">Description<textarea name="description" rows={4} defaultValue={value("description")}/></label></>}
    {type === "expense" && <><label>Date<input name="expense_date" type="date" min={LAUNCH_DATE} defaultValue={value("expense_date", new Date().toISOString().slice(0, 10))} required/></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" defaultValue={value("amount")} required/></label><label className="full">Expense item<input name="item" placeholder="Pitch repair, cricket balls, electricity…" defaultValue={value("item")} required/></label><label>Category<input name="category" list="expense-categories" defaultValue={value("category", "Maintenance")} required/><datalist id="expense-categories"><option value="Maintenance"/><option value="Equipment"/><option value="Ground supplies"/><option value="Utilities"/><option value="Staff"/><option value="Other"/></datalist></label><label>Status<select name="status" defaultValue={value("status", "Paid")}><option>Paid</option><option>Pending</option></select></label><label className="full">Details<textarea name="notes" rows={4} placeholder="Vendor, purpose, quantity, or any other details" defaultValue={value("notes")}/></label></>}
    {type === "payment" && <><label className="full">Booking<select name="booking_id" defaultValue={value("booking_id")} required disabled={editing}><option value="" disabled>Select an open booking</option>{data.bookings.filter(b => b.id === value("booking_id") || (b.status !== "Cancelled" && Number(b.balance_amount) > 0)).map(b => <option value={b.id} key={b.id}>{b.team_name} · {date(b.booking_date)} · due {money(b.balance_amount)}</option>)}</select>{editing && <input type="hidden" name="booking_id" value={value("booking_id")}/>}</label><label>Amount received<input name="amount" type="number" min="1" max={paymentMaximum} defaultValue={value("amount")} required/></label><label>Payment type<select name="payment_type" defaultValue={value("payment_type", "Advance")}><option>Advance</option><option>Balance</option><option>Full</option><option>Adjustment</option></select></label><label>Method<select name="method" defaultValue={value("method", "UPI")}><option>UPI</option><option>Cash</option><option>Bank transfer</option><option>Payment link</option><option>Other</option></select></label><label>Paid date & time<input name="paid_at" type="datetime-local" defaultValue={dateTimeInput(value("paid_at"))}/></label><label className="full">UTR / reference<input name="reference" placeholder="UPI transaction or bank reference" defaultValue={value("reference")}/></label><label className="full">Notes<textarea name="notes" rows={3} defaultValue={value("notes")}/></label></>}
    {type === "paymentRequest" && <><input type="hidden" name="booking_id" value={record?.id}/><div className="payment-request-summary full"><strong>{record?.team_name}</strong><span>{record?.client_email ? `Email to ${record.client_email}` : "No email — create a shareable payment link only"}</span><small>Current balance: {money(record?.balance_amount)}</small></div><label className="full">Amount to request<input name="amount" type="number" min="1" max={record?.balance_amount} defaultValue={Number(record?.advance_amount || 0) > 0 ? Math.min(Number(record?.advance_amount), Number(record?.balance_amount)) : record?.balance_amount} required/></label></>}
  </div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button">{type === "payment" ? "Add payment" : type === "paymentRequest" ? (record?.client_email ? "Create and email request" : "Create payment link") : type === "expense" ? (editing ? "Save expense" : "Add expense") : editing ? "Save changes" : "Save securely"}</button></div></form></div></div>;
}
