"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import { blockDate, createBooking, createClient, deleteBooking, signOut } from "./actions";

type Row = Record<string, any>;
type View = "dashboard"|"bookings"|"clients"|"payments"|"invoices"|"maintenance"|"onboarding";
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n||0);
const date=(d:string)=>d?new Date(`${d}T12:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"}):"—";

export function DashboardClient({data}:{data:{bookings:Row[];clients:Row[];expenses:Row[];invoices:Row[];maintenance:Row[];blocked:Row[]}}){
  const [view,setView]=useState<View>("dashboard"); const [modal,setModal]=useState<"booking"|"client"|"block"|null>(null); const [search,setSearch]=useState("");
  const totals=useMemo(()=>({income:data.bookings.reduce((s,b)=>s+Number(b.total_amount),0),advance:data.bookings.reduce((s,b)=>s+Number(b.advance_amount),0),balance:data.bookings.reduce((s,b)=>s+Number(b.balance_amount),0),expenses:data.expenses.reduce((s,e)=>s+Number(e.amount),0)}),[data]);
  const filtered=data.bookings.filter(b=>Object.values(b).join(" ").toLowerCase().includes(search.toLowerCase()));
  const nav:[View,string,string][]=[["dashboard","⌂","Overview"],["bookings","▦","Bookings"],["clients","♙","Clients"],["payments","₹","Payments"],["invoices","▤","Invoices"],["maintenance","◇","Maintenance"],["onboarding","✓","Onboarding"]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><Image src="/kcc-logo.jpeg" alt="KCC" width={50} height={50}/><div><strong>KCC</strong><span>Ground Admin</span></div></div><nav>{nav.map(([id,icon,label])=><button key={id} className={`nav-item ${view===id?"active":""}`} onClick={()=>setView(id)}><span className="nav-icon">{icon}</span>{label}{id==="bookings"&&<span className="nav-count">{data.bookings.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="season-card"><span>SECURE ACCESS</span><strong>KCC administrator</strong><div className="progress"><i style={{width:"100%"}}/></div><small>Authenticated database session</small></div><form action={signOut}><button className="profile-card"><span className="avatar">KCC</span><span><strong>KCC Admin</strong><small>Administrator</small></span><span>↪</span></button></form></div></aside>
  <main className="main"><header className="topbar"><div className="search"><span>⌕</span><input placeholder="Search KCC records…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="top-actions"><button className="icon-button">♢</button><button className="date-chip"><span>Secure session</span><strong>KCC Ground Admin</strong></button></div></header><div className="content">
  {view==="dashboard"&&<><Header eyebrow="GROUND OPERATIONS" title="KCC operations dashboard" subtitle="Bookings, collections, expenses, and ground activity in one secure workspace." actions={<><button className="secondary-button" onClick={()=>setModal("block")}>＋ Block date</button><button className="primary-button" onClick={()=>setModal("booking")}>＋ New booking</button></>}/><div className="metric-grid"><Metric label="TOTAL COLLECTIONS" value={money(totals.income)} note="Across recorded bookings" icon="₹"/><Metric label="ADVANCES RECEIVED" value={money(totals.advance)} note="Recorded booking advances" icon="↗"/><Metric label="OUTSTANDING BALANCE" value={money(totals.balance)} note="Payment follow-up required" icon="◷"/><Metric label="OPERATING EXPENSES" value={money(totals.expenses)} note="Tracked ground expenses" icon="⌁"/></div><div className="dashboard-grid"><Panel title="Upcoming schedule"><Schedule rows={data.bookings.slice(0,7)}/></Panel><Panel title="Quick actions"><div className="quick-actions"><button className="quick-action" onClick={()=>setModal("booking")}><span>＋</span>New booking</button><button className="quick-action" onClick={()=>setModal("client")}><span>♙</span>Add client</button><button className="quick-action" onClick={()=>setView("payments")}><span>₹</span>Payments</button><button className="quick-action" onClick={()=>setView("invoices")}><span>▤</span>Invoices</button></div></Panel></div></>}
  {view==="bookings"&&<><Header eyebrow="SCHEDULE" title="Bookings" subtitle="Manage dates, playing slots, client details, and payment status." actions={<><button className="secondary-button" onClick={()=>setModal("block")}>＋ Block date</button><button className="primary-button" onClick={()=>setModal("booking")}>＋ New booking</button></>}/><BookingTable rows={filtered}/></>}
  {view==="clients"&&<><Header eyebrow="CLIENT CRM" title="Clients" subtitle="Secure contact and team records for KCC clients." actions={<button className="primary-button" onClick={()=>setModal("client")}>＋ Add client</button>}/><DataTable headers={["Client","Team","Phone","Email","Status"]} rows={data.clients.map(c=>[c.name,c.team_name,c.phone||"—",c.email||"—",c.status])}/></>}
  {view==="payments"&&<><Header eyebrow="FINANCE" title="Payments" subtitle="Review advances, remaining balances, and operating expenses."/><div className="metric-grid"><Metric label="ADVANCES" value={money(totals.advance)} note="Received" icon="₹"/><Metric label="BALANCE DUE" value={money(totals.balance)} note="Outstanding" icon="◷"/><Metric label="EXPENSES" value={money(totals.expenses)} note="Recorded" icon="⌁"/><Metric label="NET CASH" value={money(totals.advance-totals.expenses)} note="Advances less expenses" icon="↗"/></div><DataTable headers={["Date","Expense","Category","Amount","Status"]} rows={data.expenses.map(e=>[date(e.expense_date),e.item,e.category,money(e.amount),e.status])}/></>}
  {view==="invoices"&&<><Header eyebrow="BILLING" title="Invoices" subtitle="Invoice status connected to KCC client records."/><DataTable headers={["Invoice","Issued","Client","Amount","Status"]} rows={data.invoices.map(i=>[i.invoice_number,date(i.issued_date),i.client_name,money(i.amount),i.status])}/></>}
  {view==="maintenance"&&<><Header eyebrow="GROUND CARE" title="Maintenance" subtitle="Repairs, supplies, pitch work, and recurring upkeep."/><div className="kanban">{["To do","In progress","Completed"].map(status=><section className="kanban-col" key={status}><div className="kanban-title"><span>{status.toUpperCase()}</span><span>{data.maintenance.filter(t=>t.status===status).length}</span></div>{data.maintenance.filter(t=>t.status===status).map(t=><article className="task-card" key={t.id}><span className={`status ${t.priority==="Urgent"?"urgent":"pending"}`}>{t.priority}</span><strong>{t.title}</strong><p>{t.description}</p><div className="task-meta"><span>{t.category}</span><span>{t.due_date?date(t.due_date):"No date"}</span></div></article>)}</section>)}</div></>}
  {view==="onboarding"&&<><Header eyebrow="CLIENT SETUP" title="Onboarding" subtitle="A consistent checklist for every new KCC client."/><Panel title="KCC onboarding checklist"><div className="steps">{["Contact details verified","Team profile completed","Ground rules shared","Advance received","Invoice information added","First booking confirmed"].map((s,i)=><div className="step" key={s}><span className="step-number">{i+1}</span><div><strong>{s}</strong><small>Complete this step for each new client</small></div></div>)}</div></Panel></>}
  </div></main>{modal&&<Modal type={modal} close={()=>setModal(null)}/>}</div>;
}

function Header({eyebrow,title,subtitle,actions}:{eyebrow:string;title:string;subtitle:string;actions?:React.ReactNode}){return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div><div className="header-actions">{actions}</div></div>}
function Metric({label,value,note,icon}:{label:string;value:string;note:string;icon:string}){return <article className="metric-card"><div className="metric-card-top"><span>{label}</span><span className="metric-icon">{icon}</span></div><div className="metric-value">{value}</div><div className="metric-foot">{note}</div></article>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <article className="panel"><div className="panel-header"><h2>{title}</h2></div>{children}</article>}
function Schedule({rows}:{rows:Row[]}){return <div className="schedule-list">{rows.length?rows.map(b=><div className="schedule-item" key={b.id}><div className="schedule-time"><strong>{String(b.slot).slice(0,5)}</strong><br/>{date(b.booking_date)}</div><div className="schedule-detail"><strong>{b.team_name}</strong><span>{b.captain_name}</span></div><span className={`status ${String(b.status).toLowerCase()}`}>{b.status}</span></div>):<div className="empty-state">No bookings yet.</div>}</div>}
function BookingTable({rows}:{rows:Row[]}){return <div className="table-wrap"><table><thead><tr><th>Date & slot</th><th>Team</th><th>Captain</th><th>Advance</th><th>Balance</th><th>Status</th><th/></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td>{date(b.booking_date)}<br/><small>{String(b.slot).slice(0,5)}</small></td><td><strong>{b.team_name}</strong></td><td>{b.captain_name}<br/><small>{b.phone||"Phone not added"}</small></td><td className="amount">{money(b.advance_amount)}</td><td className="amount due">{money(b.balance_amount)}</td><td><span className={`status ${String(b.status).toLowerCase()}`}>{b.status}</span></td><td><form action={deleteBooking}><input type="hidden" name="id" value={b.id}/><button className="row-button" aria-label="Remove booking">×</button></form></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state">No records found.</div>}</div>}
function DataTable({headers,rows}:{headers:string[];rows:any[][]}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty-state">No records yet.</div>}</div>}
function Modal({type,close}:{type:"booking"|"client"|"block";close:()=>void}){const action=type==="booking"?createBooking:type==="client"?createClient:blockDate;return <div className="modal"><button className="modal-backdrop" onClick={close} aria-label="Close dialog"/><div className="modal-card"><button className="modal-close" onClick={close}>×</button><span className="eyebrow">KCC SECURE RECORD</span><h2>{type==="booking"?"Add a booking":type==="client"?"Add a client":"Block a date"}</h2><form action={async(fd)=>{await action(fd);close()}}><div className="form-grid">{type==="booking"&&<><label>Date<input name="booking_date" type="date" required/></label><label>Slot<select name="slot"><option>07:00</option><option>10:30</option><option>14:00</option></select></label><label>Team<input name="team_name" required/></label><label>Captain<input name="captain_name" required/></label><label>Phone<input name="phone"/></label><label>Status<select name="status"><option>Confirmed</option><option>Pending</option><option>Cancelled</option></select></label><label>Total amount<input name="total_amount" type="number" min="0" required/></label><label>Advance<input name="advance_amount" type="number" min="0" required/></label><label className="full">Notes<textarea name="notes" rows={3}/></label></>}{type==="client"&&<><label>Name<input name="name" required/></label><label>Team<input name="team_name" required/></label><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label className="full">Notes<textarea name="notes" rows={3}/></label></>}{type==="block"&&<><label>Date<input name="blocked_date" type="date" required/></label><label>Slot<select name="slot"><option>07:00</option><option>10:30</option><option>14:00</option><option>All day</option></select></label><label className="full">Reason<input name="reason" required/></label></>}</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button">Save securely</button></div></form></div></div>}
